### ISSUE TITLE
Ability to create username using a word dictionary

### ISSUE THREAD

**Issue by You2s** [taylornetwork/laravel-username-generator#20]
Hello,

First of all, thank you for this package which looks very interesting, however, in my case I can't use it, I don't have any useful information about my users (name, email...), they are all anonymous, I was wondering if it was possible to reproduce what the [alenoir/username-generator](https://github.com/alenoir/username-generator#readme ) library made in nodeJS does and generate a username from a list of nouns (nouns.json) and adjectives (adjectives.json).

That would be very practical.

**Comment by samueljtaylor** [comment]
Hi @You2s,

I like that idea, I used the wordlists from the repo you referenced and added them to v2.3 which I've just released.

Hopefully that all works the way you intended, let me know if you have any issues or anything.

Have a great day!
