### ISSUE TITLE
Max length username

### ISSUE THREAD

**Issue by dapehe94** [taylornetwork/laravel-username-generator#33]
Hello
In the configuration I can see a variable to determine the minimum length for the username.
But is there any way to limit the maximum length?
Thank you,

**Comment by samueljtaylor** [comment]
Hi @dapehe94

Not currently, but I can definitely add that in the next version that I'm working on. Probably will release that sometime next week.

**Comment by samueljtaylor** [comment]
Hi @dapehe94 

I actually ended up having time this morning to finish up v2.5 - so I've just released that, setting maximum length of the username is in that update. 

Let me know if you have any issues with it.

Thanks,

**Comment by dapehe94** [comment]
Great!!! Faster than Louis Hamilton ;-)
Thank you very much, it works perfect!

**Comment by samueljtaylor** [comment]
Awesome, great to hear it!
