### ISSUE TITLE
Class '\App\User' not found

### ISSUE THREAD

**Issue by chadidi** [taylornetwork/laravel-username-generator#5]
I can't update the configuration using this line:
```
public function generatorConfig(&$generator)
{
    $generator->setConfig(['model' => '\App\Models\User']);
}
```

**Comment by samueljtaylor** [comment]
I can't seem to duplicate the issue on my end. Try 

```php
public function generatorConfig(&$generator)
{
    $generator->setConfig(['model' => '\\App\\Models\\User']);
}
```
OR
```php
public function generatorConfig(&$generator)
{
    $generator->setConfig(['model' => \App\Models\User::class ]);
}
```

You could also publish the config and change the model in `config/username_generator.php` 

If that doesn't work post a bit more of your code so I can try and duplicate the issue.

Thanks

**Comment by samueljtaylor** [comment]
@chadidi if you're adding the `generatorConfig` to your `App\Models\User` model you could also do:

```php
public function generatorConfig(&$generator)
{
    $generator->setConfig('model', $this);
}
```

I've tried a few other things to get the error on my end but no luck so I'm closing this issue for now. 
If you still have the issue add some more of your code so we can get it sorted out.

Thanks, 
Sam
