### ISSUE TITLE
Possible SQL-Injection?

### ISSUE THREAD

**Issue by christian98** [taylornetwork/laravel-username-generator#52]
While reading your code i stumbled accross the following line ([FindSimilarUsernames.php#L77](https://github.com/taylornetwork/laravel-username-generator/blob/master/src/FindSimilarUsernames.php#L77)): 
```php
return static::whereRaw("$column REGEXP '{$username}([0-9]*)?$'")->get();
```

Is the `whereRaw` necessary? Although you are stripping unwanted characters, this might lead to SQL-Injections, no? If a developer using your package does not know about this specific implementation and overwrites the `allowed_characters` Config-option and adds 'danagerous' characters, a user could inject SQL into the query by specifying a username.
I actually dont know much about `REGEXP`, but i am think that there has to be a way to use prepared statements here.

I found the following on [laracasts](https://laracasts.com/discuss/channels/eloquent/using-regexp-in-where?page=1&replyId=444206):
```php
$fulfills = Dialog::where('external_id', 'regexp', 'T[0-9]+')->get();
```

Which leads me to suggest something like this:
```php
private function searchUsingRegexp(string $username)
{
    return static::where($this->getColumn(), 'REGEXP', $username."([0-9]*)?$")->get();
}
```

I'm actually not 100% sure if this fixes the SQL-Injection problem and still provide the same functunality.

**Comment by samueljtaylor** [comment]
@christian98 

Thank you for bringing this to my attention! 

Fortunately the `$username` string doesn't hit the database until it's undergone the conversions to make it more like a username. So it shouldn't be an issue in almost all cases.

That being said I'm releasing v2.6.2 which fixes it.
